swagger: '2.0'
info:
  version: '0.1.0'
  title: API Pokemon
  description: An API to manage pokemon
host: 192.168.99.100
basePath: /api
schemes:
  - http
paths:
  /pokemons:
    get:
      description: get the list of all pokemons
      operationId: getPokemons
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          type: string
          description: name of the pokemon to return
        - in: query
          name: type
          type: string
          description: type of the pokemon to return
        - in: query
          name: category
          type: string
          description: category of the pokemon to return
        - in: query
          name: height
          type: integer
          description: height of the pokemon to return
        - in: query
          name: hp
          type: integer
          description: hp of the pokemon to return
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Pokemon'
    delete:
      operationId: deletePokemons
      description: delete the list of all pokemons
      parameters:
        - in: query
          name: name
          type: string
          description: name of the pokemon to delete
        - in: query
          name: type
          type: string
          description: type of the pokemon to delete
        - in: query
          name: category
          type: string
          description: category of the pokemon to delete
        - in: query
          name: height
          type: integer
          description: height of the pokemon to delete
        - in: query
          name: hp
          type: integer
          description: hp of the pokemon to delete
      responses:
        204:
          description: sucessfully deleted
    
    post:
      description: create a pokemon
      operationId: createPokemon
      consumes:
        - application/json
      parameters:
        - name: pokemon
          in: body
          required: true
          schema:
            $ref: '#/definitions/Pokemon'
      responses:
        '201':
          description: created
          schema:
            $ref: '#/definitions/Pokemon'
  /pokemons/{id}:
    get:
      description: get a pokemon by its ID
      operationId: getPokemonByID
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Pokemon'
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The pokemon ID
    delete:
      description: delete a pokemon by its ID
      operationId: deletePokemonByID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The pokemon ID
      responses:
        204:
          description: sucessfully deleted
    patch:
      description: update a pokemon by its ID
      operationId: updatePokemonByID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The pokemon ID
        - name: pokemon
          in: body
          required: true
          schema:
            $ref: '#/definitions/Pokemon'
      responses:
        200:
          description: success
    
    
    
definitions:
  Pokemon:
    type: object
    properties:
      pokedexId:
        type: integer
      name:
        type: string
      type:
        type: string
      category:
        type: string
      height:
        type: integer
      hp:
        type: integer
      