swagger: '2.0'
info:
  version: '0.1.0'
  title: Users for Pokemon API
  description: An API to manage users for Pokemon API
host: localhost:8090
basePath: /api/login
schemes:
  - http
paths:
  /login:
    post:
      description: login to get JWT Token
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credentials
          in: body
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: logged successfully
          schema:
            $ref: '#/definitions/ValidCreds'
        '401':
          description: bad login
  /users:
    get:
      description: get user info
      operationId: getUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        '201':
          description: retrieved account info
          schema:
            $ref: '#/definitions/UserToGet'
    post:
      description: create an account
      operationId: createAccount
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserToPost'
      responses:
        '201':
          description: account created
          schema:
            $ref: '#/definitions/UserToGet'
        '403':
          description: Access denied

  /password:
    put:
      description: change password for its own account
      operationId: changePassword
      consumes:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: body
          name: queryPassword
          required: true
          schema:
            $ref: '#/definitions/QueryPasswordChange'
      responses:
        '201':
          description: account created
          schema:
            $ref: '#/definitions/UserToGet'
definitions:
  BaseUser:
    type: object
    properties:
      username:
        type: string
      mail:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      isadmin:
        type: boolean
  UserToPost:
    allOf:
      - type: object
        required:
          - password
        properties:
          password:
            type: string
      - $ref: '#/definitions/BaseUser'

  UserToGet:
    allOf:
      - type: object
        required:
          - id
        properties:
          id:
            type: integer
      - $ref: '#/definitions/BaseUser'

  QueryPasswordChange:
    type: object
    properties:
      currentPassword:
        type: string
      newPassword:
        type: string
  Credentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  ValidCreds:
    type: object
    properties:
      JWTToken:
        type: string
      userID:
        type: integer
